spring:
  messages:
    basename: i18n.universal #国际化 引入路径
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/JIeY2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.jie.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  servlet:
    encoding:
      enabled: true